# Generated by Django 5.0.2 on 2024-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
    ]
