# Generated by Django 5.0.9 on 2024-09-10 11:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_data_urodzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pesel',
            field=models.CharField(max_length=11, null=True, validators=[core.models.validate_pesel]),
        ),
    ]
