# Generated by Django 5.0.9 on 2024-09-10 14:17

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[core.models.validate_pesel]),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tour_type', models.CharField(choices=[('SR', 'Seniorski'), ('JR', 'Juniorski'), ('MA', 'Master')], max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('money_prize', models.IntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Męski'), ('FEMALE', 'Żeński')])),
                ('date_of_beginning', models.DateField()),
                ('date_of_finishing', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
