# Generated by Django 5.0.9 on 2024-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_player_user_user_data_urodzenia_user_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='teams',
        ),
        migrations.AddField(
            model_name='tournament',
            name='ranking_type',
            field=models.CharField(choices=[('NoneRank', 'Bezrankingowy'), ('OneStar', '1 gwiazdka'), ('TwoStars', '2 gwiazdki'), ('ThreeStars', '3 gwiazdki')], default='NoneRank'),
        ),
    ]
