# Generated by Django 5.0.9 on 2024-09-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournamentresult_tournament_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
