# Generated by Django 5.0.9 on 2024-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Męski'), ('FEMALE', 'Żeński')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tournament_points',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
