# Generated by Django 5.0.9 on 2024-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tournament_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Męski'), ('FEMALE', 'Żeński')], max_length=6)),
                ('rankings', models.JSONField()),
            ],
        ),
    ]
