---
name: Check and Lint

on:
    push:

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Checkout
                uses: actions/checkout@v4.1.1
            -   name: Test
                uses: docker-compose run --rm app sh -c "python manage.py test"
            -   name: Lint
                uses: docker-compose run --rm app sh -c "python manage.py flake8"

